### ISSUE TITLE
Accept File Paths Without Specifying Put

### ISSUE THREAD

**Issue by mcmah309** [umlx5h/gtrash#11]
Instead of
```console
gtrash put path/to/file
```
It would be nice if
```console
gtrash path/to/file
```
also worked. Many users, including myself, creating shell functions for trash like
```sh
trash() {
    gtrash put "$@"
}
# Or
rm() {
    gtrash put "$@"
}
```
But if we do this then
```sh
trash --help
```
does not work as expected. This may also work better when interacting with other programs and scripts.

**Comment by umlx5h** [comment]
Sorry this is intentional, i chose the sub commands design because I want it to be featureful and single binary.

If you do not want to type sub commands such as 'gtrash put', you can set an alias or create a wrapper script to the following.

https://github.com/umlx5h/gtrash?tab=readme-ov-file#can-i-run-trash-put-in-one-command-without-using-alias

```
$ sudo vim /usr/local/bin/trash
#!/bin/sh

# Specify gtrash binary path
exec /usr/local/bin/gtrash put "$@"

$ sudo chmod a+x /usr/local/bin/trash

$ trash somefile
```

Since trash-cli is normally used 99% of the time for deleting files, it seems reasonable to use aliases or the wrapper only there. Operations such as restore do not require aliases for me.

I'm not interested in implementing 'put syntax sugar' because usually aliases and the wrapper are enough and it will introduce side effects such as the following.

* can not delete a file with same name as a subcommand, e.g. `put`, `restore`
* incompatible with shell auto-completion
* it may be dangerous

**Comment by umlx5h** [comment]
> But if we do this then trash --help does not work as expected.

You can set an alias instead of function, then `--help` will work

zsh
```bash
$ alias tt="gtrash put"

$ tt --help
Description:
  A substitute for 'rm', moving files to the trash.
```
