### ISSUE TITLE
Support macOS trash can($HOME/.Trash)

### ISSUE THREAD

**Issue by y-vectorfield** [umlx5h/gtrash#4]
According to the README, this command does not support the macOS system trash can.
Can this tool deal with this for `$HOME/.Trash`?
If this function is implemented, the Mac user can use this conveniently.

**Comment by umlx5h** [comment]
I do not plan to support native trash cans on macOS at this time.
The main reason is that the same information as `FreeDesktop` is not likely to be available from the `~/.Trash/.DS_Store` file.
The FreeDesktop spec requires the following information, but I have not confirmed that all of this can be obtained.

1. Original Path
2. Deletion Date

reference:
https://ponderthebits.com/2017/01/mac-dumpster-diving-identifying-deleted-file-references-in-the-trash-ds_store-files-part-1/

Since this DS_Store file does not have a published specification, I determined that it would be too costly to support.

The FreeDesktop spec could be applicable to UNIX, since macOS is a real UNIX, I though there are no particular problems with using it on macOS.

If you want to use the system trash on macOS, I recommend using an alternative tool such as following.
https://hasseg.org/trash/

**Comment by y-vectorfield** [comment]
@umlx5h 
Thank you very much for your advice!

**Comment by jozef-koval-prewave** [comment]
> [@umlx5h](https://github.com/umlx5h) 

https://formulae.brew.sh/formula/trash is what you look for.
