### ISSUE TITLE
DOesnt show trashed file from other program

### ISSUE THREAD

**Issue by og900aero** [umlx5h/gtrash#8]
I use Debian 12 Stable.

My trash folder is /home/Data/.Trash

When I issue the next command: gtrash put file , then put file to the /home/Data/.Trash and all fines.
But I delete other files with (example) Transmission-gtk program, the files delete to /home/Data/.Trash, but the gtrash program doesnt see these files.

**Comment by umlx5h** [comment]
Since this program is implemented in XDG's Trash specification
Moving files directly under the Trash directory will not be recognized.

Please read the instructions in README.md.
https://github.com/umlx5h/gtrash?tab=readme-ov-file#how-it-works

Is the Trash directory as follows? Is the file directly placed in the Trash directory?

```
$ ls ~/.local/share/Trash/
files  info  directorysizes
```

If you want to work with other programs, use an application that supports the XDG trash can.
If it is not supported, unfortunately it cannot be linked with this program.

**Comment by og900aero** [comment]
Thx for your reply.
